# ~/environment/sam-app/buildspec.yml

version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      # Install packages or any pre-reqs in this phase.
      # Upgrading SAM CLI to latest version
      - pip3 install --upgrade aws-sam-cli
      - sam --version
      # Installing project dependencies
      - cd hello_world
      #- npm install

  pre_build:
    commands:
      # Run tests, lint scripts or any other pre-build checks.
      #- python -m unittest discover tests

  build:
    commands:
      # Use Build phase to build your artifacts (compile, etc.)
      - cd ..
      - sam build

  post_build:
    commands:
      # Use Post-Build for notifications, git tags, upload artifacts to S3
      #- sam package --s3-bucket $PACKAGE_BUCKET --output-template-file packaged.yaml
      - sam package --s3-bucket accenturecloud --output-template-file outputtemplate.yml
      #- aws cloudformation package --template-file template.yml --s3-bucket accenturecloud --output-template-file outputtemplate.yml
      #- sam package --s3-bucket accenturecloud --output-template-file template.yaml

artifacts:
  type: zip
  files:    
    - outputtemplate.yml
